web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  container_name: rho-gitlab
  hostname: 'gitlab.rhomicom.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.rhomicom.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '5999:80'
    #- '443:443'
    #- '22:22'
  volumes:
    - './gitlab/config:/etc/gitlab'
    - './gitlab/logs:/var/log/gitlab'
    - './gitlab/data:/var/opt/gitlab'
